services:
  app:
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_REPO}:latest
    ports:
      - "4000:3000"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    restart: always

volumes:
  redis_volume: